version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: 
      context: ./JAMIE
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - backend